# Generated by Django 3.2.18 on 2023-02-18 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('intro', tinymce.models.HTMLField()),
                ('email', models.CharField(default='', max_length=1000)),
                ('image', models.CharField(default='', max_length=1000)),
                ('dribble', models.CharField(default='', max_length=1000)),
                ('instagram', models.CharField(default='', max_length=1000)),
                ('behance', models.CharField(default='', max_length=1000)),
                ('role', models.CharField(default='Designer', max_length=1000)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1055, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('percentage', models.CharField(max_length=1000)),
                ('years', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', tinymce.models.HTMLField()),
                ('images', models.ManyToManyField(to='project.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('role', models.CharField(default='', max_length=1000)),
                ('description', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(blank=True, max_length=1055, null=True)),
                ('video', models.CharField(blank=True, max_length=1055, null=True)),
                ('active', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='project.projecttype')),
                ('sections', models.ManyToManyField(to='project.Image')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
