# Generated by Django 3.2.18 on 2023-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_myclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='upwork',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
