# Generated by Django 3.2.18 on 2023-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
    ]
