# Generated by Django 3.2.18 on 2023-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='central_image',
            field=models.CharField(blank=True, help_text='To appear between the sections in project view', max_length=1055, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_image',
            field=models.CharField(blank=True, help_text='To appear as the big image on top of the page when you open a single project', max_length=1055, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='To appear as the preview image on the home page', max_length=1055, null=True),
        ),
    ]
